#!/usr/bin/env python

Import("env")
Import("env_modules")
import methods

env_godot_module = env_modules.Clone()

if methods.using_clang(env_godot_module) or methods.using_emcc(env_godot_module):
    env_godot_module.Append(CXXFLAGS=["-frelaxed-template-template-args"])

env_godot_module.add_source_files(env.modules_sources, "*.cpp")
env_godot_module.add_source_files(env.modules_sources, "components/*.cpp")
env_godot_module.add_source_files(env.modules_sources, "components/physics/*.cpp")
env_godot_module.add_source_files(env.modules_sources, "nodes/*.cpp")
env_godot_module.add_source_files(env.modules_sources, "databags/*.cpp")
env_godot_module.add_source_files(env.modules_sources, "systems/*.cpp")

if env_godot_module.editor_build:
    env_godot_module.add_source_files(env.modules_sources, "editor_plugins/*.cpp")
