#!/usr/bin/env python

Import('env')
Import('env_modules')

env_dem_bones = env_modules.Clone()

env_dem_bones.Prepend(CPPPATH=['.'])
env_dem_bones.Prepend(CPPPATH=['include'])
env_dem_bones.Prepend(CPPPATH=['#modules/dem_bones/thirdparty/eigen'])
env_dem_bones.Prepend(CPPPATH=['#modules/dem_bones/thirdparty/eigen/Eigen'])
env_thirdparty = env_dem_bones.Clone()

env_dem_bones.add_source_files(env.modules_sources, "*.cpp")