#!/usr/bin/env python

Import("env")
env.Append(LIBS=["mfplat", "mf", "wmcodecdspuuid", "mfuuid", "mfreadwrite"])
Import("env_modules")

env_wmf = env_modules.Clone()

env_wmf.add_source_files(env.modules_sources, "*.cpp")
Export("env")
