#!/usr/bin/env python

Import("env")
env_thirdparty = env.Clone()
env_thirdparty.Append(CPPDEFINES=[("EIGEN_HAS_STD_RESULT_OF", 0)])
env_thirdparty.Prepend(CPPPATH=["#thirdparty/eigen"])
env_thirdparty.Prepend(CPPPATH=["#modules/lbfgs"])
env_thirdparty.Prepend(CPPPATH=["#modules/lbfgs/src"])
env_thirdparty.Prepend(CPPPATH=["#modules/lbfgs/thirdparty/LBFGSpp/include"])

env_lbfgs = env_thirdparty.Clone()
env_lbfgs.disable_warnings()
env_lbfgs.add_source_files(env.modules_sources, "thirdparty/*.cpp")

env_thirdparty.add_source_files(env.modules_sources, "*.cpp")
