#!/usr/bin/env python

Import("env")
env_lbfgs = env.Clone()
env_lbfgs.Append(CPPDEFINES=[("EIGEN_HAS_STD_RESULT_OF", 0)])
env_lbfgs.Prepend(CPPPATH=["#thirdparty/eigen"])
env_lbfgs.Prepend(CPPPATH=["#modules/lbfgs"])
env_lbfgs.Prepend(CPPPATH=["#modules/lbfgs/src"])
env_lbfgs.Prepend(CPPPATH=["#modules/lbfgs/thirdparty/LBFGSpp/include"])
env_lbfgs.add_source_files(env.modules_sources, "src/*.cpp")
env_lbfgs.add_source_files(env.modules_sources, "*.cpp")
